"use client";
import {useEffect,useRef,useState} from "react";import {Moon,Plus,Sun} from "lucide-react";import {Composer} from "./composer";import {Message,type ChatMessage} from "./message";import type {StreamEvent} from "@/lib/stream/events";
const suggestions=["Explain the Klarna Network Session flow","What events should I listen to in the Web SDK?","Help me debug an authorization integration","Explain Payment Presentation like I’m new to KN"];
export function ChatShell(){const [messages,setMessages]=useState<ChatMessage[]>([]);const [summary,setSummary]=useState("");const [busy,setBusy]=useState(false);const [tool,setTool]=useState("");const [dark,setDark]=useState(false);const [resetKey,setResetKey]=useState(0);const controller=useRef<AbortController|null>(null);
 useEffect(()=>{const saved=localStorage.getItem("lebayon-theme");const value=saved?saved==="dark":matchMedia("(prefers-color-scheme: dark)").matches;setDark(value);document.documentElement.dataset.theme=value?"dark":"light"},[]);const toggle=()=>{const value=!dark;setDark(value);document.documentElement.dataset.theme=value?"dark":"light";localStorage.setItem("lebayon-theme",value?"dark":"light")};
 const reset=()=>{controller.current?.abort();setMessages([]);setSummary("");setTool("");setBusy(false);setResetKey(k=>k+1)};
 const send=async(content:string)=>{if(busy)return;const user:ChatMessage={id:crypto.randomUUID(),role:"user",content,sources:[],charts:[],images:[]};const assistant:ChatMessage={id:crypto.randomUUID(),role:"assistant",content:"",sources:[],charts:[],images:[],streaming:true};const history=[...messages,user];setMessages([...history,assistant]);setBusy(true);const abort=new AbortController();controller.current=abort;try{const response=await fetch("/api/chat",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({messages:history.map(({role,content})=>({role,content})),summary}),signal:abort.signal});if(!response.ok){const body=await response.json().catch(()=>({})) as {error?:string};throw new Error(body.error||`The chat service returned HTTP ${response.status}.`)}const reader=response.body!.getReader(),decoder=new TextDecoder();let buffer="";while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const parts=buffer.split("\n\n");buffer=parts.pop()||"";for(const part of parts){const line=part.split("\n").find(x=>x.startsWith("data: "));if(!line)continue;const event=JSON.parse(line.slice(6)) as StreamEvent;setMessages(current=>current.map(m=>m.id!==assistant.id?m:applyEvent(m,event)));if(event.type==="tool_started")setTool(event.label);if(event.type==="tool_finished")setTool("");if(event.type==="summary_update")setSummary(event.summary);if(event.type==="error")throw new Error(event.message)}}}catch(e){if(!abort.signal.aborted)setMessages(current=>current.map(m=>m.id===assistant.id?{...m,content:m.content||`I couldn’t send that request. ${e instanceof Error?e.message:"Something went wrong."}`,streaming:false}:m))}finally{setBusy(false);setTool("");setMessages(current=>current.map(m=>m.id===assistant.id?{...m,streaming:false}:m))}};
 return <div className="app"><header className="header"><div className="brand"><div className="mark" aria-hidden><svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M5 4v16M5 12h8m0-6v12m0-6 6-5m-6 5 6 5" strokeWidth="2" strokeLinecap="round"/></svg></div><div><div className="logo">LeBayon</div><div className="descriptor">Klarna Network Expert</div></div></div><div className="actions"><button className="new-btn" onClick={reset}><Plus size={17}/><span>New chat</span></button><button className="icon-btn" onClick={toggle} aria-label={`Use ${dark?"light":"dark"} theme`}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button></div></header><main className="main">{messages.length===0?<section className="empty"><div className="eyebrow">Solution &amp; Delivery companion</div><h1>G&apos;day. LeBayon here.</h1><p>Klarna Network questions, integration mysteries, SDK existential crises — chuck them my way. We&apos;ll make the complicated bits behave.</p><div className="suggestions">{suggestions.map(s=><button className="suggestion" key={s} onClick={()=>send(s)}>{s}</button>)}</div></section>:<div className="messages">{messages.map(m=><Message key={m.id} message={m}/>)}{tool&&<div className="tool" role="status"><span className="spinner"/>{tool}</div>}</div>}</main><Composer onSend={send} disabled={busy} resetKey={resetKey}/></div>}
function applyEvent(m:ChatMessage,e:StreamEvent):ChatMessage{switch(e.type){case"text_delta":return{...m,content:m.content+e.delta};case"source":return{...m,sources:m.sources.some(s=>s.url===e.source.url)?m.sources:[...m.sources,e.source]};case"chart":return{...m,charts:[...m.charts,e.chart]};case"image":return{...m,images:[...m.images,{url:e.url,alt:e.alt}]};case"done":return{...m,streaming:false};default:return m}}
