import { readFile } from "node:fs/promises";
import { describe, expect, it, vi } from "vitest";
import { crawl, extractPage, splitText, valid } from "./sync-klarna-docs";
const fixture = () => readFile(new URL("./__fixtures__/network-session.html", import.meta.url), "utf8");
describe("Klarna crawler", () => {
  it("scopes and normalizes URLs", () => { expect(valid("/klarna-network-distribution/web-sdk/?a=1#x")).toBe("https://docs.klarna.com/klarna-network-distribution/web-sdk/"); expect(valid("https://evil.test/klarna-network-distribution/")).toBeNull(); expect(valid("/payments/")).toBeNull(); });
  it("honors canonical URLs and preserves code and tables", async () => { const page = extractPage(await fixture(), "https://docs.klarna.com/klarna-network-distribution/old/#x"); expect(page.canonicalUrl).toContain("/api/network-session/"); expect(page.links).toEqual(["https://docs.klarna.com/klarna-network-distribution/api/network-session/", "https://docs.klarna.com/klarna-network-distribution/web-sdk/"]); const authorization = page.chunks.find((c) => c.heading === "Authorization")!; expect(authorization.text).toContain("```\nconst session"); expect(authorization.text).toContain("| Event | Meaning |"); expect(new Set(page.chunks.map((c) => c.id)).size).toBe(page.chunks.length); });
  it("chunks content without losing it", () => { const input = `${"one ".repeat(30)}\n\n${"two ".repeat(30)}`; const parts = splitText(input, 100); expect(parts.length).toBeGreaterThan(1); expect(parts.join(" ")).toContain("one"); expect(parts.join(" ")).toContain("two"); });
  it("deduplicates canonical pages", async () => { const html = await fixture(); const fetcher = vi.fn(async () => new Response(html)); const chunks = await crawl({ seeds: ["https://docs.klarna.com/klarna-network-distribution/old/", "https://docs.klarna.com/klarna-network-distribution/new/"], maxPages: 2, concurrency: 2, delayMs: 0, minCharacters: 1, fetcher }); expect(chunks.filter((c) => c.heading === "Authorization")).toHaveLength(1); });
  it("fails rather than overwriting on empty extraction", async () => { const fetcher = vi.fn(async () => new Response("<main></main>")); await expect(crawl({ seeds: ["https://docs.klarna.com/klarna-network-distribution/empty/"], delayMs: 0, minCharacters: 1, fetcher })).rejects.toThrow("refusing to replace"); });
});
