import type Anthropic from "@anthropic-ai/sdk";import {z} from "zod";import {chartSchema} from "@/lib/validation/schemas";import {searchKlarnaDocs} from "@/lib/tools/klarna-docs";import {searchWeb} from "@/lib/tools/perplexity";import {generateImage} from "@/lib/tools/openai-image";
export const toolDefinitions:Anthropic.Tool[]=[
 {name:"search_klarna_network_docs",description:"Search the official Klarna Network corpus and live-verify canonical pages. Mandatory before KN technical claims.",input_schema:{type:"object",properties:{query:{type:"string"},domainHint:{type:"string"}},required:["query"]}},
 {name:"search_web",description:"Research current wider-web information with Perplexity. Not a substitute for KN documentation.",input_schema:{type:"object",properties:{query:{type:"string"}},required:["query"]}},
 {name:"generate_image",description:"Generate an inline image when explicitly requested or genuinely useful.",input_schema:{type:"object",properties:{prompt:{type:"string"},sizeIntent:{type:"string",enum:["square","portrait","landscape"]},context:{type:"string"}},required:["prompt"]}},
 {name:"create_chart",description:"Render validated quantitative data as an inline chart.",input_schema:{type:"object",properties:{type:{type:"string",enum:["line","bar","area","pie","donut"]},title:{type:"string"},labels:{type:"array",items:{type:"string"}},series:{type:"array",items:{type:"object",properties:{name:{type:"string"},data:{type:"array",items:{type:"number"}}},required:["name","data"]}},xAxisLabel:{type:"string"},yAxisLabel:{type:"string"}},required:["type","title","labels","series"]}}
];
const query=z.object({query:z.string().min(2).max(1000)}),image=z.object({prompt:z.string().min(3).max(4000),sizeIntent:z.enum(["square","portrait","landscape"]).optional(),context:z.string().max(1000).optional()});
export async function executeTool(name:string,input:unknown){if(name==="search_klarna_network_docs")return searchKlarnaDocs(query.parse(input).query);if(name==="search_web")return searchWeb(query.parse(input).query);if(name==="generate_image"){const v=image.parse(input);return generateImage(`${v.prompt}${v.context?`\nContext: ${v.context}`:""}`,v.sizeIntent)}if(name==="create_chart")return{chart:chartSchema.parse(input)};throw new Error("Unknown tool")}
